# Generated by Django 5.1.1 on 2024-10-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationalpathway',
            options={'ordering': ['sequence'], 'verbose_name': 'Conversational Pathway', 'verbose_name_plural': 'Conversational Pathways'},
        ),
        migrations.AddField(
            model_name='agent',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversationalpathway',
            name='bland_ai_pathway_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='bland_ai_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
