# Generated by Django 5.1.1 on 2024-10-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_conversationalpathway_options_agent_version_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationalpathway',
            options={'ordering': ['sequence']},
        ),
        migrations.AlterField(
            model_name='agent',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
