# Generated by Django 5.1.1 on 2024-10-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_alter_conversationalpathway_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='html_input',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='script',
        ),
        migrations.AddField(
            model_name='agent',
            name='analysis_schema',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='dynamic_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='first_sentence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='interruption_threshold',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='agent',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='language',
            field=models.CharField(default='ENG', max_length=10),
        ),
        migrations.AddField(
            model_name='agent',
            name='max_duration',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='agent',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='model',
            field=models.CharField(default='enhanced', max_length=50),
        ),
        migrations.AddField(
            model_name='agent',
            name='pathway_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='prompt',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='agent',
            name='tools',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='voice',
            field=models.CharField(default='default_voice', max_length=100),
        ),
    ]
