# Generated by Django 5.1.1 on 2024-10-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_remove_agent_html_input_remove_agent_script_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='script',
            field=models.TextField(blank=True, null=True),
        ),
    ]
