# Generated by Django 5.1.1 on 2024-10-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agent_script'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationalpathway',
            options={},
        ),
        migrations.RemoveField(
            model_name='conversationalpathway',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='conversationalpathway',
            name='content',
        ),
        migrations.RemoveField(
            model_name='conversationalpathway',
            name='sequence',
        ),
        migrations.AddField(
            model_name='conversationalpathway',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationalpathway',
            name='edges',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationalpathway',
            name='name',
            field=models.CharField(default='default_name', max_length=255),
        ),
        migrations.AddField(
            model_name='conversationalpathway',
            name='nodes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationalpathway',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='conversationalpathway',
            name='bland_ai_pathway_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
