# Generated by Django 5.1.1 on 2024-10-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_alter_conversationalpathway_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationalpathway',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='conversationalpathway',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agent',
            name='bland_ai_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='prompt',
            field=models.TextField(),
        ),
    ]
