# Generated by Django 5.1.1 on 2024-10-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_alter_conversationalpathway_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='bland_ai_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
