# Generated by Django 5.1.1 on 2024-10-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_agent_webhook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationalpathway',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
